version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: ember-cli-babel
    versions:
    - 7.23.1
  - dependency-name: ember-cli-typescript
    versions:
    - 4.0.0
    - 4.1.0
  - dependency-name: prettier
    versions:
    - 2.2.1
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: semver
    versions:
    - 7.3.4
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.0
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.0.1
