name: CI Build

on:
  push:
    branches:
      - master
      - 'v*'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # daily, at 3am

jobs:
  test:
    timeout-minutes: 10
    name: "Tests: ${{ matrix.EMBROIDER && 'embroider' || 'classic' }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        EMBROIDER:
          - '' # classic
          - 'true'

    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - run: pnpm lint
      - run: pnpm test:ember
        working-directory: test-apps/base-tests
        env: 
          EMBROIDER: ${{ matrix.EMBROIDER }}

  floating-dependencies:
    timeout-minutes: 10
    name: "Floating Dependencies: ${{ matrix.EMBROIDER && 'embroider' || 'classic' }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        EMBROIDER:
          - '' # classic
          - 'true'

    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - run: pnpm test:ember
        working-directory: test-apps/base-tests
        env: 
          EMBROIDER: ${{ matrix.EMBROIDER }}

  typecheck:
    name: '${{ matrix.typescript-scenario }}'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    continue-on-error: true
    strategy:
      fail-fast: true
      matrix:
        typescript-scenario:
          - typescript@5.0
          - typescript@5.1
          - typescript@5.2
          - typescript@5.3
          - typescript@5.4

    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - run: pnpm prepack
        working-directory: ./addon/

      - name: 'Change base tests TS to ${{ matrix.typescript-scenario }}'
        run: 'pnpm add --save-dev ${{ matrix.typescript-scenario}}'
        working-directory: ./test-apps/base-tests/

      - name: 'Change ember-concurrency TS to ${{ matrix.typescript-scenario }}'
        run: 'pnpm add --save-dev ${{ matrix.typescript-scenario}}'
        working-directory: ./test-apps/ember-concurrency-v2

      - name: 'Change ember-fetch TS to ${{ matrix.typescript-scenario }}'
        run: 'pnpm add --save-dev ${{ matrix.typescript-scenario}}'
        working-directory: ./test-apps/ember-fetch-v8

      - run: pnpm --filter "*" test:ts;


  try-scenarios:
    timeout-minutes: 10
    name: "Try: ${{ matrix.ember-try-scenario }} @ ${{ matrix.app }}"

    runs-on: ubuntu-latest

    needs: test

    strategy:
      fail-fast: false
      matrix:
        app: 
          - test-apps/base-tests
          - test-apps/ember-concurrency-v2
          - test-apps/ember-fetch-v8
        ember-try-scenario:
          - ember-lts-3.16
          - ember-lts-3.20
          - ember-lts-3.24
          - ember-lts-3.28
          - ember-lts-4.12
          - ember-lts-5.4
          - ember-release
          - ember-beta
          - ember-canary
          - 3.x-embroider-safe
          - 3.x-embroider-optimized

    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: 18.18.1
      - name: test
        run: node_modules/.bin/ember try:one ${{ matrix.ember-try-scenario }} --skip-cleanup
        working-directory: ${{ matrix.app }}
